{-
   Brainrex API Explorer

   Welcome to the Brainrex API explorer, we make analytics tools for crypto and blockchain. Our currently propiertary models offer sentiment analysis, market making, blockchain monitoring and face-id verification. This AI models can be consumed from this API. We also offer integrations to open data and propietary data providers, as well as free test data we collect. There is a collection of data transformation tools. Join our Telegram group to get the latest news and ask questions [https://t.me/brainrex, #brainrex](https://t.me/brainrex). More about Brainrex at [https://brainrex.com](http://brainrex.com). Full Documentation can be found at [https://brainrexapi.github.io/docs](https://brainrexapi.github.io/docs)

   OpenAPI spec version: 2.0
   Brainrex API Explorer API version: 0.1.1
   Contact: support@brainrex.com
   Generated by Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
-}

{-|
Module : BrainrexAPIExplorer.API
-}

module BrainrexAPIExplorer.API
  ( module BrainrexAPIExplorer.API.Blockchain
  , module BrainrexAPIExplorer.API.Crypto
  , module BrainrexAPIExplorer.API.SentimentAnalysis
  ) where

import BrainrexAPIExplorer.API.Blockchain
import BrainrexAPIExplorer.API.Crypto
import BrainrexAPIExplorer.API.SentimentAnalysis